n=input('Digite algo:')
print('Segue abaixo os tipos')
print('Tipo primitivo:', type(n))
print('É alfabetico?', n.isalpha())
print('É númerico?', n.isnumeric())
print('É alfanúmerico?', n.isalnum())
print('Só recebe espaço?', n.isspace())
print('Tem letra maiuscula?', n.isupper())
print('Tem letra minuscula?', n.islower())
print('Tem capitalização?', n.istitle())

